Add Configuration and Install pages
stake-house/wagyu-installer pull request #91
Opened 2022-06-03 22:54 UTC by qu0b

2022-06-07 18:15 UTC, qu0b commented
I've updated the dialog

2022-06-10 18:24 UTC, remyroy commented on src/react/components/ImportKeystore.tsx
> +import { Network } from '../types';
and could be removed

2022-06-10 19:06 UTC, remyroy requested changes
Some changes are needed. I could do them myself if you want.

2022-06-10 19:06 UTC, remyroy commented on src/react/pages/SystemOverview.tsx
>  import { Network } from "../types";
Unused import. Could be removed.

2022-06-10 19:30 UTC, qu0b commented on src/react/components/ImportKeystore.tsx
> +import { Network } from '../types';
fixed

2022-06-10 19:34 UTC, qu0b commented on src/react/components/ImportKeystore.tsx
> +// console.log(dialog.showOpenDialog({ properties: ['openFile'] }))
fixed

2022-06-10 19:38 UTC, qu0b commented on src/react/constants.ts
> +	label: 'Geth (recommended)',
I could implement a random order for the next release

2022-06-10 19:40 UTC, qu0b commented
I think I resolved all of the changes, could you make sure that it still runs in your VM before releasing it?

2022-06-10 19:51 UTC, merged

2022-06-10 19:51 UTC, remyroy commented
Everything is good. Merging.